import eulJson from "@eulerxyz/euler-interfaces/abis/Eul.json";
import eulerJson from "@eulerxyz/euler-interfaces/abis/Euler.json";
import pTokenJson from "@eulerxyz/euler-interfaces/abis/PToken.json";
import eTokenJson from "@eulerxyz/euler-interfaces/abis/modules/EToken.json";
import dTokenJson from "@eulerxyz/euler-interfaces/abis/modules/DToken.json";
import execJson from "@eulerxyz/euler-interfaces/abis/modules/Exec.json";
import liquidationJson from "@eulerxyz/euler-interfaces/abis/modules/Liquidation.json";
import marketsJson from "@eulerxyz/euler-interfaces/abis/modules/Markets.json";
import swapJson from "@eulerxyz/euler-interfaces/abis/modules/Swap.json";
import swapHubJson from "@eulerxyz/euler-interfaces/abis/modules/SwapHub.json";
import eulStakesJson from "@eulerxyz/euler-interfaces/abis/mining/EulStakes.json";
import eulDistributorJson from "@eulerxyz/euler-interfaces/abis/mining/EulDistributor.json";
import eulerLensV1Json from "@eulerxyz/euler-interfaces/abis/views/EulerLensV1.json";

export const eul = eulJson.abi;
export const euler = eulerJson.abi;
export const pToken = pTokenJson.abi;
export const eToken = eTokenJson.abi;
export const dToken = dTokenJson.abi;
export const exec = execJson.abi;
export const liquidation = liquidationJson.abi;
export const markets = marketsJson.abi;
export const swap = swapJson.abi;
export const swapHub = swapHubJson.abi;
export const eulStakes = eulStakesJson.abi;
export const eulDistributor = eulDistributorJson.abi;
export const eulerLensV1 = eulerLensV1Json.abi;